#!/usr/bin/env python3
"""Bake ground tile PNGs into main/game/assets/tiles.hpp as RGB565 arrays.

Source tiles live in the repo at art/tiles/. Pure stdlib PNG decode
(zlib + unfilter) -- supports 8-bit RGB (colortype 2) / RGBA (6), non-interlaced, which
is what these tiles are. RGB565 uses the SAME formula as engine/gfx.hpp so tile colors
match the palette. Run from the repo root: python tools/gen_tiles.py [grass.png dirt.png]
"""
import zlib, struct, sys, os

def rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)

def load_png_rgb(path):
    with open(path, "rb") as f:
        data = f.read()
    assert data[:8] == b"\x89PNG\r\n\x1a\n", f"not a PNG: {path}"
    pos, w, h, bitd, ct, interlace, idat = 8, 0, 0, 0, 0, 0, b""
    while pos < len(data):
        ln = struct.unpack(">I", data[pos:pos + 4])[0]
        typ = data[pos + 4:pos + 8]
        chunk = data[pos + 8:pos + 8 + ln]
        if typ == b"IHDR":
            w, h, bitd, ct = struct.unpack(">IIBB", chunk[:10])
            interlace = chunk[12]
        elif typ == b"IDAT":
            idat += chunk
        elif typ == b"IEND":
            break
        pos += 12 + ln
    assert bitd == 8 and ct in (2, 6), f"unsupported PNG (bitdepth {bitd}, colortype {ct})"
    assert interlace == 0, "interlaced PNG not supported"
    ch = 3 if ct == 2 else 4
    raw = zlib.decompress(idat)
    stride = w * ch
    prev = bytearray(stride)
    rows, i = [], 0
    for _ in range(h):
        ft = raw[i]; i += 1
        line = bytearray(raw[i:i + stride]); i += stride
        if ft == 1:      # Sub
            for x in range(ch, stride): line[x] = (line[x] + line[x - ch]) & 0xFF
        elif ft == 2:    # Up
            for x in range(stride): line[x] = (line[x] + prev[x]) & 0xFF
        elif ft == 3:    # Average
            for x in range(stride):
                a = line[x - ch] if x >= ch else 0
                line[x] = (line[x] + ((a + prev[x]) >> 1)) & 0xFF
        elif ft == 4:    # Paeth
            for x in range(stride):
                a = line[x - ch] if x >= ch else 0
                b = prev[x]
                c = prev[x - ch] if x >= ch else 0
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                pr = a if (pa <= pb and pa <= pc) else (b if pb <= pc else c)
                line[x] = (line[x] + pr) & 0xFF
        elif ft != 0:
            raise ValueError(f"bad filter type {ft}")
        prev = line
        rows.append([(line[x * ch], line[x * ch + 1], line[x * ch + 2]) for x in range(w)])
    return w, h, rows

def emit(name, w, h, rows):
    flat = [rgb565(*rows[y][x]) for y in range(h) for x in range(w)]
    lines = []
    for i in range(0, len(flat), 12):
        lines.append("    " + " ".join("0x%04X," % v for v in flat[i:i + 12]))
    return f"static const uint16_t {name}[{w * h}] = {{\n" + "\n".join(lines) + "\n};"

def main():
    args = sys.argv[1:]
    here = os.path.dirname(__file__)
    grass = args[0] if len(args) > 0 else os.path.join(here, "..", "art", "tiles", "ground-grass-1.png")
    dirt  = args[1] if len(args) > 1 else os.path.join(here, "..", "art", "tiles", "ground-dirt-1.png")

    gw, gh, grows = load_png_rgb(grass)
    dw, dh, drows = load_png_rgb(dirt)
    assert (gw, gh) == (dw, dh), "tiles must share dimensions"
    print(f"grass {gw}x{gh} from {grass}")
    print(f"dirt  {dw}x{dh} from {dirt}")

    out = os.path.join(os.path.dirname(__file__), "..", "main", "game", "assets", "tiles.hpp")
    with open(os.path.abspath(out), "w", newline="\n") as f:
        f.write(f"""#pragma once
#include <cstdint>

// Baked ground tiles (RGB565, opaque). Repeated across the ground band by
// gfx_tile_region(). GENERATED by tools/gen_tiles.py from the source PNGs -- edit
// those + regenerate, not this file.
static constexpr int TILE_W = {gw};
static constexpr int TILE_H = {gh};

// grass surface (top row of the ground)
{emit("grass_tile", gw, gh, grows)}

// dirt below the grass
{emit("dirt_tile", dw, dh, drows)}
""")
    print("wrote", os.path.abspath(out))

if __name__ == "__main__":
    main()
