#!/usr/bin/env python3
"""Generate main/game/assets/sprites.hpp: a single 48x48 RGB565 "?" placeholder.

Drawn whenever a creature's real (PNG) sprite can't be shown. White glyph + dark
outline so it stays legible on any background (sky/grass/panel). Transparent pixels
use the 0xF81F color key (SPRITE_TRANSP, defined in engine/gfx.hpp). Pure stdlib,
no Pillow. Run from the repo root: python tools/gen_fallback_sprite.py
"""
import math, os

W = H = 48
TRANSP = 0xF81F

def rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)

FILL    = rgb565(245, 245, 250)   # near-white glyph body
OUTLINE = rgb565(20, 20, 30)      # near-black halo

# --- build the "?" stroke path (round-pen), then rasterize -------------------
cx = 24.0
ink = [[False] * W for _ in range(H)]

def stamp(px, py, r):
    x0, x1 = int(px - r) - 1, int(px + r) + 1
    y0, y1 = int(py - r) - 1, int(py + r) + 1
    for y in range(max(0, y0), min(H, y1 + 1)):
        for x in range(max(0, x0), min(W, x1 + 1)):
            if (x + 0.5 - px) ** 2 + (y + 0.5 - py) ** 2 <= r * r:
                ink[y][x] = True

def stroke(pts, r):
    for (ax, ay), (bx, by) in zip(pts, pts[1:]):
        d = math.hypot(bx - ax, by - ay)
        n = max(1, int(d / 0.5))
        for i in range(n + 1):
            t = i / n
            stamp(ax + (bx - ax) * t, ay + (by - ay) * t, r)

PEN = 3.3
# top loop: arc over the top, from lower-left (200deg) round to lower-right (-35deg)
loop, a = [], 200.0
cyc, R = 16.5, 9.5
while a >= -35.0:
    rad = math.radians(a)
    loop.append((cx + R * math.cos(rad), cyc - R * math.sin(rad)))
    a -= 5.0
# tail: bend the stroke down and back to a centered vertical stem
loop += [(cx + 3.5, 24.5), (cx + 0.8, 27.0), (cx, 29.0), (cx, 31.5)]
stroke(loop, PEN)
# the dot
stamp(cx, 38.5, PEN + 0.2)

# --- outline: transparent pixels touching ink (8-neighbourhood) --------------
px = [[TRANSP] * W for _ in range(H)]
for y in range(H):
    for x in range(W):
        if ink[y][x]:
            px[y][x] = FILL
        else:
            near = any(0 <= y + dy < H and 0 <= x + dx < W and ink[y + dy][x + dx]
                       for dy in (-1, 0, 1) for dx in (-1, 0, 1))
            if near:
                px[y][x] = OUTLINE

# --- ASCII preview -----------------------------------------------------------
print("preview (# fill, + outline, . clear):")
for y in range(H):
    print("".join("#" if px[y][x] == FILL else "+" if px[y][x] == OUTLINE else "."
                  for x in range(W)))

# --- emit the header ---------------------------------------------------------
flat = [px[y][x] for y in range(H) for x in range(W)]
lines = []
for i in range(0, len(flat), 12):
    lines.append("    " + " ".join("0x%04X," % v for v in flat[i:i + 12]))
body = "\n".join(lines)

out = os.path.join(os.path.dirname(__file__), "..", "main", "game", "assets", "sprites.hpp")
with open(os.path.abspath(out), "w", newline="\n") as f:
    f.write(f"""#pragma once
#include <cstdint>

// Baked-in fallback bitmap: a question mark, drawn whenever a creature's real (PNG)
// sprite can't be shown -- not yet decoded, decode failed, or no creature data
// loaded at all. RGB565; the 0xF81F pixels are the transparent color key
// (SPRITE_TRANSP, defined in engine/gfx.hpp) and blit as clear.
//
// GENERATED by tools/gen_fallback_sprite.py -- edit that, not this.
#define SPRITE_W 48
#define SPRITE_H 48
static const uint16_t spr_unknown_data[{W * H}] = {{
{body}
}};
""")
print("\nwrote", os.path.abspath(out))
